### ISSUE TITLE
Arbeitsdokument "Was ist eine gute KPI?" erstellen?

### ISSUE THREAD

**Issue by vroland** [serlo/p_data-analysis-and-kpis#105]

**Comment by kulla** [comment]
Unter https://serlo.slack.com/archives/CFBR6F7NZ/p1568671246002900 habe ich mal gefragt, ob es ein solches Dokument bereits gibt. Wie ich heute erfahren habe, ist die U Controlling für dieses Thema eigentlich zuständig.

**Comment by kulla** [comment]
Update: Es gibt noch kein Dokument und U Controlling dankt uns, dass wir so ein Dokument erstellen.

**Comment by Adrian-Bischoff** [comment]
Link zum Dokument.
https://docs.google.com/document/d/1fok2QMoDaXnv3p6Z90fwHxsfHXuFJ4M3Ofl3J2gTWXU/edit
