### ISSUE TITLE
Nachhaltig DSGVO - Konformität schaffen

### ISSUE THREAD

**Issue by vroland** [serlo/p_data-analysis-and-kpis#113]
Für die Auswertung von Nutzerbezogenen KPIs muss deren Zustimmung eingeholt werden.
Dieser Prozess muss entworfen werden.

- [x] Datenschutzerklärungs-Änderung entwerfen (#8)
- [x] Datenschutzerklärung feedbacken (#110)
- [x] Datenschutzerklärung im Deutschen updaten ( https://github.com/serlo/serlo.org/pull/296 )
- [x] Datenschutzerklärung ins Englische übersetzen (#117 )
- [x] Datenschutzerklärung verändern (#116 )
- [ ] Finalen merge abwarten...

**Comment by Knorrke** [comment]
Does this affect serlo.org or only the dashboard? The privacy policy of serlo.org is versionized and if users haven't accepted the currently active version yet, they will see a banner asking for approval. The versions are requested from a json API.

**Comment by Lodifice** [comment]
It will affect serlo.org, because data of every author is collected.

We have shortly thought about spreading the new version of the privacy policy, e.g. sending via E-mail. It's good to know that there is a centralized approach.

**Comment by vroland** [comment]
@Knorrke Could you point us to where to find this information in the database (if it is there)?

**Comment by Knorrke** [comment]
no, its handled directly in the code: The valid revisions are defined here: https://github.com/serlo/serlo.org/blob/bcac71a87ddaed6cbb5e75fbca1f485d1d0570a3/packages/public/server/src/module/StaticPage/config/module.config.php#L127-L132

The templates that are rendered for the privacy policy page are located here: https://github.com/serlo/serlo.org/tree/84c1230c0e0bc0776bc1eca9a2b422470eeacf45/packages/public/server/src/module/Ui/templates/static/de/datenschutz

And this is the Controller handling the JSON-Requests for revisions and rendering the templates https://github.com/serlo/serlo.org/blob/bcac71a87ddaed6cbb5e75fbca1f485d1d0570a3/packages/public/server/src/module/StaticPage/src/StaticPage/Controller/DatenschutzController.php#L59-L73

**Comment by vroland** [comment]
@Knorrke As I am not familiar with Athene: How can we determine the currently accepted revision for each user?

**Comment by kulla** [comment]
Under https://github.com/serlo/serlo.org/tree/feature/new-privacy-revision I prepare the update of the the privacy policy (I will open the PR after I have finished the update - I have a remaining little open issue)

**Comment by Knorrke** [comment]
> @Knorrke As I am not familiar with Athene: How can we determine the currently accepted revision for each user?

This is currently only handled in localstorage. I can look up the key, if you need it? We probably will move this into the new user-field table someday, now that https://github.com/serlo/serlo.org/pull/77 is merged.
