### ISSUE TITLE
Bug: Data in dashboard not up to date

### ISSUE THREAD

**Issue by yolo-bird** [serlo/p_data-analysis-and-kpis#135]
All charts in the dashboard do not contain data after the 16th of december.

**Comment by Lodifice** [comment]
FYI I just created https://github.com/serlo/infrastructure-env-staging/pull/5/files

As soon as this is merged (staging), we'll merge into production.

**Comment by Lodifice** [comment]
It's deployed on Staging now, can you please have a look whether the data seems reasonable? The gap between August and December should soon be fixed.

**Comment by Lodifice** [comment]
Is deployed on production.
