### ISSUE TITLE
Can the dashboard be accessable without password?

### ISSUE THREAD

**Issue by kulla** [serlo/p_data-analysis-and-kpis#30]
@yolo-bird @SimonKoehl Was denkt ihr? Ist es in Ordnung, wenn das Dashboard ohne Passwortschutz frei verfügbar ist? So haben alle (auch die Autor*innen-Community) Zugang zu den Zahlen.

**Comment by yolo-bird** [comment]
Müsste man sich als kurz überlegen, ob es KPI's gibt, die man z.B. gegenüber Förderern nicht live haben möchte. Spontan sehe ich bei allen sehr wichtigen KPI's (Nutzerzahlen, aktive Autor*innen) keine Bedenken

**Comment by SimonKoehl** [comment]
Bin erstmal d'accord mit voller Transparenz

**Comment by kulla** [comment]
Danke für eure Antwort. So wie es aktuell aussieht, kommt ein passwortfreies Dashboard erst in einem zweiten Schritt.  #35 ist als Follow-Up notiert.
