### ISSUE TITLE
DNS: Grafana soll unter stats.serlo.org zugänglich sein

### ISSUE THREAD

**Issue by kulla** [serlo/p_data-analysis-and-kpis#38]

**Comment by marinusma** [comment]
Grundsätzlich wurde die Subdomain **stats.** integriert. Für die zwei unterschiedlichen Systemumgebungen **production** und **staging** lauten die URLs derzeit wie folgt:

- http://stats.staging.serlo.org
- http://stats.production.serlo.org (temporär)

Die finale Umstellung der Subdomains für **production** kann erst zu einem späteren Zeitpunkt geschehen und kann in folgendem Ticket verfolgt werden:
https://github.com/serlo/infrastructure/issues/7

**Comment by kulla** [comment]
@marinusma Dank dir für die Umsetzung! Wundere dich nicht, dass ich das issue erst jetzt schließe. Mein Firefox hat automatisch auf HTTPS redirected (was aber mit #42 gelöst werden wird). Mit Chromium funktioniert bei mir alles bestens.
