### ISSUE TITLE
Kulla: Minikube zum Laufen bringen

### ISSUE THREAD

**Issue by kulla** [serlo/p_data-analysis-and-kpis#52]

**Comment by rbock44** [comment]
Minikube läuft jetzt bei Richard und Valentine.
Ich hab noch ein Skript geschrieben das automatisch die komplette Testumgebung aufsetzt.

**Comment by rbock44** [comment]
läuft.

**Comment by rbock44** [comment]
Ups. Sorry. Ich glaube der ist für Dich :-)

**Comment by kulla** [comment]
Mein Vorgehen:

1) Docker nach https://docs.docker.com/install/linux/docker-ce/debian/ installieren
2) Libvirt nach https://medium.com/linagora-engineering/install-k8s-minikube-on-top-of-kvm-on-debian-9-9cd5b646063c installieren
3) Minikube und Terraform mit asdf installieren
4) Install Gcloud and gsutil ( https://cloud.google.com/sdk/install bzw https://cloud.google.com/storage/docs/gsutil_install#deb )
5) Anonymous Dump herunterladen
6) jq installieren

-> Muss ich noch überprüfen, ob man dieses in `README.md` übernehmen kann...
