### ISSUE TITLE
Dashboard: Histogramm über aktuelle Review-Zeiten (letzte 90 Tage)

### ISSUE THREAD

**Issue by kulla** [serlo/p_data-analysis-and-kpis#76]

**Comment by vroland** [comment]
@kulla Hier müssen wir nochmal überlegen, da gerade für die aktuellen edits das ganze nicht wirklich aussagekräftig ist, da wir wirklich lang ausstehenden Reviews (>90 Tage) ja noch ausstehen und somit gar nicht dort auftauchen.

**Comment by kulla** [comment]
@vroland Verwende folgende Definition:

Histogramm Reviewzeiten aller Bearbeitungen, die noch offen sind oder die in den letzten 90 Tagen erstellt wurden. Ich würde also die offenen Bearbeitungen noch hinzunehmen.

**Comment by Lodifice** [comment]
Deployed and running.
