### ISSUE TITLE
Dashboard: Anzahl (aktive / sehr aktive) Reviewer*innen

### ISSUE THREAD

**Issue by kulla** [serlo/p_data-analysis-and-kpis#78]
Definition: Dashboard mit Anzahl Reviewer, Anzahl aktive Reviwer, Anzahl sehr aktive Reviewer pro Tag (wie beim Anzahl Autor*innen Dashboard). Definitionen:

* Reviewer: Mindestens eine Reviewing-Bearbeitung in den letzten 90 Tagen
* aktive Reviewer: Mindestens 10 Reviewing-Bearbeitung in den letzten 90 Tagen
* sehr aktive Reviewer: Mindestens 100 Reviewing-Bearbeitung in den letzten 90 Tagen
* Reviewing-Bearbeitung: Review-Accept oder Review-Deny bei einer fremden Bearbeitung (Review eigener Bearbeitungen, insbesondere automatische Reviews sind ausgeschlossen)

**Comment by Lodifice** [comment]
Deployed and running.
