### ISSUE TITLE
Grafana Domain von "localhost:3000" in aktuelle Domain ändern

### ISSUE THREAD

**Issue by kulla** [serlo/p_data-analysis-and-kpis#81]
Wenn man aktuell einen neuen User anlegt, wird im Invitelink "https://localhost:3000" angezeigt -> dies müsste geändert werden

**Comment by rbock44** [comment]
added a root url now so this should be fixed latest on Monday.

**Comment by rbock44** [comment]
Is pushed to DEV cluster.
