### ISSUE TITLE
Zeitfenster Review-Zeiten ändern auf Bearbeitungen in einer Woche / an einem Tag -> mit Variables lösbar?

### ISSUE THREAD

**Issue by kulla** [serlo/p_data-analysis-and-kpis#94]

**Comment by Lodifice** [comment]
Maybe https://grafana.com/docs/reference/templating/ is the way?

**Comment by Lodifice** [comment]
It' easily possible, see 6f36a9d9473752629993d97af310a7f5d4b8802e.

The only room for improvement I see the the duplication of SQL queries in the aggregator.

**Comment by Lodifice** [comment]
Deployed and running.
